### ISSUE TITLE
3D optimization

### ISSUE THREAD

**Issue by MRdaizr** [stanfordnqp/spins-b#1]
Hello, this is a great program, and I want to test, but there are some problems.
Can this be designed in 3D? If this can be done, what should I do?
I tried to change the variable SIM_2D to False, but something went wrong with the program.
Thanks.

**Comment by ludi1001** [comment]
The reason is that the 3D solver hasn't been released yet. It's coming soon!

**Comment by ludi1001** [comment]
The solver has been released at stanfordnqp/maxwell-b
