### ISSUE TITLE
grating example: how to optimize shorter grating?

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#12]
I am wondering, how can I limit the length of the rating? Currently the simulation domain is 16 microns long, and grating starts 2 microns from left end (i.e., solid waveguide is always 2 microns long). And the grating is roughly 12 microns long (with 2 microns of empty space on the right). But for my tightly focused Gaussian beam half of the grating is nearly useless. Is it possible to shorten the length of the optimized grating? And how? Thank you in advance!

**Comment by VovaZen** [comment]
Found answer myself - one needs to modify sizes in sim_bg.gds and sim_fg.gds files, and also in the script - modify simulation domain size, size of Gaussian beam input and position of the calculating overlap for the waveguide.

**Comment by VovaZen** [comment]
How about to add it as enhancement, i.e., get rid of gds files needed for grating script and instead write grating parameters (i.e., length of solid waveguide on the left side of simulation domain and length of the empty space on the right side of simulation domain) in the script itself?

**Comment by ludi1001** [comment]
The purpose of the example was partially to illustrate how the GDS file system works for a different type of problem. Actually for myself, I have a script that draws the GDS files I need (using gdspy). Will consider adapting it to this problem in particular

**Comment by ludi1001** [comment]
Grating length is now a parameter that can be controlled in the example.
