### ISSUE TITLE
grating example - view command

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#13]
After optimization, when I use 'view' command, sometimes it says something like not enough memory. It looks like it is trying to load all files from each optimization step at once, and for many steps (like 500) it becomes huge amount of memory. But for 'view' it needs only to plot like power vs. step and field at last point. Can it instead load optimization steps one-by-one, take power, and close file? Another option: why not combine run with view commands, so that those figures will be produces automatically after the optimization script stops?

**Comment by ludi1001** [comment]
Yes, this is on our todo list :) Actually Pickle files aren't the best for compact storage either...

As a workaround, you can choose not save the field/permittivity every single iteration. This will significantly reduce memory consumption both on the filesystem and when loading the files.

**Comment by VovaZen** [comment]
Could you please expand how to not save  field/permittivity every single iteration? And only save it, for example, for the last step?

**Comment by ludi1001** [comment]
When setting the `optplan.ScipyOptimizerMonitorList`, you specify which monitors to save at the start of the transformation (`start_monitors`), at the end of the transformation (`end_monitors`), and during each iteration (`callback_monitors`). Suppose I have `mon_field` that monitors the electric field slice and `mon_obj` that monitors the objective function value, then this would save only `mon_obj` each iteration and `mon_field` at the end of the transformation:

```python

optplan.Transformation(
            name="opt_cont",
            parametrization=cont_param,
            transformation=optplan.ScipyOptimizerTransformation(
                optimizer="L-BFGS-B",
                objective=obj,
                monitor_lists=optplan.ScipyOptimizerMonitorList(
                    callback_monitors=[mon_obj],
                    start_monitors=[mon_obj],
                    end_monitors=[mon_obj, mon_field],
                optimization_options=optplan.ScipyOptimizerOptions(
                    maxiter=cont_iters),
            )
```

**Comment by VovaZen** [comment]
Thanks!

**Comment by ludi1001** [comment]
Grating example updated. `python3 grating.py view_quick save-folder` will now quickly print out the scalar monitors (e.g. power) onto the console.
