### ISSUE TITLE
extract grating widths after optimization

### ISSUE THREAD

**Issue by joamatab** [stanfordnqp/spins-b#15]
I run an optimization for a 220nm height (70nm etch), and I get a result

10*np.log10(0.61) = -2.14 dB

which makes sense (on Lumerical I get slightly better result)

How can i extract the widths of the different grating widths after optimization?

with open("./save-folder/step255.pkl", "rb") as fp:
    data = pickle.load(fp)
    print(data['parametrization'])

what does this parametrization mean? It should be an array of interleaved withs, gaps

{'vector': array([  5.        ,   8.98772728,  12.97674666,  15.47738019,
         20.20773896,  24.99917227,  27.99609812,  30.50119184,
         33.00119184,  42.19753236,  44.99641153,  55.91701248,
         59.12187749,  68.86095872,  73.17755064,  82.70590249,
         86.96690846,  95.97138631, 102.63545175, 109.62749898,
        116.47864432, 123.99428874, 131.28258405, 138.13824982,
        145.8695731 , 152.43608324, 160.00187742, 166.88243873,
        174.27293068, 181.25168036, 188.99850018, 195.08167309,
        203.00287036, 209.50210436, 217.99906239, 222.00578535,
        224.50578535, 227.00578535, 232.00122492, 236.9989287 ,
        239.4989287 , 241.9989287 , 246.00969753, 251.00078296,
        253.50078296, 256.00078296, 261.00022745, 265.49581954,
        267.99581954, 270.49581954, 275.00007453, 279.38741164,
        281.99991055, 285.00023287, 288.5       , 291.        ,
        293.5       , 296.        ])}

**Comment by VovaZen** [comment]
Try to multiply it by optimization parameter dx. Does it make sense? The waveguide itself goes from -infinity to 0.

**Comment by ludi1001** [comment]
The parametrization values correspond to locations of grating edges in units of dx. So as @VovaZen suggested, multiply the numbers by dx to get the locations.

Unfortunately, the waveguide doesn't necessarily start at location zero, and there's not an easy way of figuring that out right now (you have to look at the pixel value at the edge of the waveguide to figure out how the permittivity averaging is performed). We have a way of avoiding this issue, and we'll fix ASAP.

**Comment by VovaZen** [comment]
Logan is right regarding waveguide edge - please see my comments in #11. Also this is linked to #14.

**Comment by ludi1001** [comment]
In the most recent update, the grating parametrization used in the example is now inverted so that first number in the parametrization corresponds to the falling edge instead of a rising edge. Therefore, you should be able to just multiple the parametrization vector by dx to get the location of the edges, without worrying about where the start of the waveguide.
