### ISSUE TITLE
broadband optimization - please add del (ratio) function to optplan

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#16]
I am playing with broadband optimization of grating coupler, i.e., in order to get a reasonable efficiency values for selected wavelengths (1400, 1450, 1500, 1550, 1600 nm). It seems that the final result depends very much on how the objective is defined. In wdm example it defines it as simply a sum for different wavelengths:
obj = (1-P_1400)^2 + (1-P_1450)^2 + ... + (1-P_1600)^2
However, in such way it seems that some wavelengths are sacrificed in favor of others (i.e., instead of providing a flat efficiency at all wavelength, it gives configuration with very low efficiency for one/few wavelengths and high efficiency for another wavelength(s)).
In order to get more flat response (at least to avoid strong drops in efficiency), I use product for objective:
obj =  (1-P_1400) * (1-P_1450) * ... * (1-P_1600)
This seems to work to some extent, but I also thought that it could be useful to define objective in a way that it changes faster for low P and slow for high P. Such behavior can be done by defining objective in a following (reciprocal or inverted) way:
obj =  1/(A+P_1400) + 1/(A+P_1450) + ... + 1/(A+P_1600),
where A is a free parameter to define threshold (for example, assume A = 0.5, corresponding to the efficiency of 50%).
However, when I type the above expression in the script code, it doesn't work, because P is a special data type 'power', and division is not defined for it. As I can see, basic operations for 'power' are defined in  spins/invdes/problem_graph/optplan/schema_function.py. Could you please add divide function to it?

**Comment by VovaZen** [comment]
I experienced a bit with different definitions of objective. There is a difference, but not significant. I use the following simple one and it works fine:
obj = (1-P_1400) + (1-P_1450) + ... + (1-P_1600)

**Comment by VovaZen** [comment]
Small update: a reasonable idea for broadband optimization is to maximize the smallest power of the spectrum (or, with the same logic, minimize the largest 1-P). That is, ideal objective is
obj = max(1-P), where maximum is among all observed monitors (in my case I needed to set them in a step of 20 nm). However, since power is not just a number, one cannot directly calculate its maximum. Instead one can use algebraic expression:
max(1-P) = sum((1-P)^n) for n --> infinity. To make it simple, one can use n = 2 and get back to the default (proposed in another example) objective:
obj = (1-P_1400)^2 + (1-P_1450)^2 + ... + (1-P_1600)^2

**Comment by ludi1001** [comment]
For many wavelengths, we also use LogSumExp. It's currently implemented in the optimization code layer but not visible all the way up in optplan. I'll open a public issue for this.
