### ISSUE TITLE
Surface SoftmaxAverage to optplan

### ISSUE THREAD

**Issue by ludi1001** [stanfordnqp/spins-b#18]
For use in multiple wavelength optimization. 

See #16

**Comment by VovaZen** [comment]
Could you please explain a bit more what it does and how to use it?

**Comment by ludi1001** [comment]
See `spins.invdes.problem.objective.SoftmaxAverage`. It needs to be able to exposed up the stack to optplan for you to be able to use it easily (hence the bug)

**Comment by JesseLu** [comment]
Closing this for now.
