### ISSUE TITLE
GDS Generation

### ISSUE THREAD

**Issue by kwadwo00** [stanfordnqp/spins-b#2]
How do you export a gds from an optimization?
Is the "generate_polygons" parameter active anywhere or is there another method?

**Comment by ludi1001** [comment]
Since spins-b only has continuous optimization (besides gratings), the device itself is never technically discrete. Therefore, there isn't technically a pre-defined way to turn a structure into a set of polygons for a GDS file. That said, we'll probably add a function to output approximate polygons from a continuous structure in the next release.

**Comment by MKAbdElrahman** [comment]
I'm facing the same problem in JuliaFDFD. Sometimes the resulting devices gave a nearly  defined polygon structure and the approximation can be done  manually.  May be some Image processing to recognize the structures in the device is needed.

**Comment by ludi1001** [comment]
In our case, the continuous parametrization is done using a bicubic interpolation, so we could in principal just "threshold" the device (i.e. find the intersection of the bicubically-interpolated function with the value equal to the average of the foreground and background permittivities) and extract precise polygons out that way.

**Comment by kwadwo00** [comment]
I put together a workaround using PIL and Nazca for the time being, but definitely let me know if you have a better way to do it.

This is just a simple threshold implementation, so it works for the bulk images, but may be one unit off at the edges of features. (e.g. +/- 40 nm for the input waveguide on the wdm2 example, but the output waveguides match exactly)

https://github.com/kwadwo00/spins-b/blob/master/examples/wdm2/monitor_processing_example.ipynb

**Comment by 2iw31Zhv** [comment]
Recently I also wrote some [code](https://gist.github.com/2iw31Zhv/c30e8d239566a07b25264495f2e25a39) based on gdspy (but with a new version 1.4.2 compared to spins-b). 

It utilizes boolean operation to merge the small rectangles so loading gdspy to verify the performance would become faster. Although it also has the offset issue mentioned above.

**Comment by ludi1001** [comment]
For the invdes branch, `CubicParametrization` has a `generate_polygons` which approximates a discrete polygon from the continuous structure (basically we're taking the contours of the bicubic inteprolated function used to define the continuous parametrization). The GDS should also now automatically be generated (for invdes).
