### ISSUE TITLE
grating coupling - how about plasmonic structures?

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#20]
I am wondering, whether it is possible to implement the script in order to optimize the grating for plasmonic waveguide? For example, for the simplest case with semi-infinite metal (gold) and air above. As it is now, there is a fixed discretization size which wouldn't work for metal (the mesh size should be much smaller inside the metal). Maybe the negative epsilon of metal will be another issue...

**Comment by ludi1001** [comment]
There's partial support for non-uniform meshing, but as it is not well-tested, we haven't really exposed it to the full interface. As it is a 2D simulation, you could try optimizing at the finer discretization level. Negative (and complex) permittivity should be fine.

**Comment by VovaZen** [comment]
I am also a bit concerned regarding using continuous optimization step, since average permittivity for metal might not work...

**Comment by kaipengliuHIT** [comment]
> There's partial support for non-uniform meshing, but as it is not well-tested, we haven't really exposed it to the full interface. As it is a 2D simulation, you could try optimizing at the finer discretization level. Negative (and complex) permittivity should be fine. 

oh，the spins can solve the optimization problems of metal structure with complex epsilon？

**Comment by JesseLu** [comment]
Closing this for now. Please let us know if this worked for you, or if this is still an issue.
