### ISSUE TITLE
Issues while installing spins-b on Anaconda on window 10

### ISSUE THREAD

**Issue by Prettzz** [stanfordnqp/spins-b#24]
Hi,
I tried to install spins-b on Python 3.7.4 by command pip install ./spins-b. But it is showing that it "failed building wheel for gdspy" . I am using window 10.
I need help regarding that.

Thanks

**Comment by ludi1001** [comment]
Please follow the installation directions for Windows for gdspy: https://github.com/heitzmann/gdspy

**Comment by kaipengliuHIT** [comment]
I can install the spinsb, but I couldn't run it because of ModuleNotFoundError: No module named 'spins'

**Comment by Guobiao-Tang** [comment]
Yes, it is. That's a very big problem many people meet and couldn't find a solution.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaipeng Liu"<notifications@github.com&gt;; 
发送时间: 2020年5月2日(星期六) 晚上9:47
收件人: "stanfordnqp/spins-b"<spins-b@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [stanfordnqp/spins-b] Issues while installing spins-b on Anaconda on window 10 (#24)





 
I can install the spinsb, but I couldn't run it because of ModuleNotFoundError: No module named 'spins'

**Comment by kaipengliuHIT** [comment]
And put the run file in the same folder, although there is no error, but the program does not respond

**Comment by msu627** [comment]
Hi, is the ModuleNotFoundError issue solved? I also got the same problem.

**Comment by AhmedHBayoumi** [comment]
Hi @kaipengliuHIT , @msu627 , and @Guobiao-Tang 

You could solve this issue by either: 

1- Simply copy-pasting spins folder inside the directory that has the python file you are executing.

2- Adding spins as a package in the python paths. Whenever you import a package, Python looks for it in some directories on your PC. You can find them by executing the following on Python:

`import sys
print (sys.path)`

This will output the paths python looks for when you use a package (such as spins). You may copy spins to one of those paths, or you may define a new path that has spins. How this is done depends on your operating system but for linux you edit your .bashrc file and add this to it

`export PYTHONPATH="${PYTHONPATH}:/my/other/path"
`
You may check this: https://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath

**Comment by kaipengliuHIT** [comment]
> Hi @kaipengliuHIT , @msu627 , and @Guobiao-Tang
> 
> You could solve this issue by either:
> 
> 1- Simply copy-pasting spins folder inside the directory that has the Python file you are executing.
> 
> 2- Adding spins as a package in the Python paths. Whenever you import a package, Python looks for it in some directories on your PC. You can find them by executing the following on Python:
> 
> `import sys`
> `print (sys.path)`
> 
> This will output the paths that Python looks for when you use a package (such as spins). You may copy spins to one of those paths, or you may define a new path that has spins. How this is done depends on your operating system, for linux you edit your .bashrc file and add this to it
> 
> `export PYTHONPATH="${PYTHONPATH}:/my/other/path" `
> 
> You may check this for further details: https://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath

Thank you!!!

**Comment by JesseLu** [comment]
Closing this.
