### ISSUE TITLE
3D GDS Usage

### ISSUE THREAD

**Issue by iclibera** [stanfordnqp/spins-b#30]
Hi,

At my first 3D inverse design wdm2 trial, I obtain the following with sim_fg and bg integrated as other layers on it.
![gds_output](https://user-images.githubusercontent.com/21977248/81835231-afeec200-954a-11ea-8cfa-007ab13de115.png)

At this stage, I am using my laptop to run 3D simulation, so I wanted to ask a few questions beforehand:

**First question (which I am about to check from the code, but just wanted make sure):** I just changed SIM_2D as False for 3D computation and as I have not changed inside of simulation area, I guess I am having this inconsistency with input GDS, am I right?

and

**Second question is,** is that possible to easily produce these GDS files for your example of TE-TM splitter (if so, would you give a clue, where to focus on)? Plus, is that possible to obtain 3D view graphics as you do in your articles? I am posting the example you posted on your website below:

![te-tm](https://user-images.githubusercontent.com/21977248/81835725-41f6ca80-954b-11ea-8ace-6984ca91a3ab.png)

Thank you in advance,

Bera

**Comment by ludi1001** [comment]
1. Just be clear, you're overlaying the designed device with the original simulation region? That might actually be a bug where the GDS generation is scaling things up by a factor of 2... If you scale the design down by factor 2, does it look like what you're supposed to get?

2. I think those were designed by a graduate student who graduated over a decade ago, so I don't know where the GDS files for those designs are anymore. That said, it shouldn't be hard to re-optimize one using the current code. Currently, to create any 3D device images, we just use Blender.

**Comment by iclibera** [comment]
Hi Logan,

I am grateful for your answers, it really makes big difference for a newbie like me.

As you stated earlier, yes there might be a bug in production of the output as the input and output GDS does not seem to fit each other; but, I have not got there back again as I am digging down into the SPINS code. I will add a comment if I am getting the same problematic result again.

Now, although the origin of the question changing direction here, I just wanted to write down under this heading as this is a follow-up question:

In order to create _TE/TM_ modes and simulate it (let's say I want an example design of a _TE/TM splitter_), would changing the definition WaveguideModeSource and WaveguideModeOverlap be enough? As I go deep down in the code, I can see the calculations are done, but is that the key step to change "**extents**" parameter of the **WaveguideModeSource**, for example, to reach a TM or TE kind mode?

Or should I change go down and change much basic stuff in the **waveguide_mode.py** (which leads to a **def solve_waveguide_mode_3d** and some other)?

Thank you

**Comment by ludi1001** [comment]
The scaling issue has been fixed in the latest push.
