### ISSUE TITLE
Verification of Example wdm2.py in Lumerical FDTD

### ISSUE THREAD

**Issue by iclibera** [stanfordnqp/spins-b#32]
Hi,

Is there a specific way of verifying this on Lumerical or possible might be me having trouble in my setup, but when I run wdm2.py example without touching anything and importing the output gds file on Lumerical FDTD and then importing default sim_bg.gds from /spins-b/examples/invdes/wdm2, and then finally simulate it as in wdm2.py (applying a source just like the one in the code), I do not observe the same result as in the output monitors of Spins. Rather, when I apply 1300 and 1550nm I always get high power out of the upper arm of it, but simply nothing is ejected through the lower arm.

Is that possible that I may be having a wrong setup, or is that possible that we need to change stuff from wdm2.py to obtain an output just like in the Spins monitors (of the default Github clone)

**Comment by ludi1001** [comment]
One possibility is that there was a GDS generation bug (now fixed) that made the GDS polygons twice as large as they were supposed to be.

Second, in the example, we aren't careful to make the optimized structure as discrete as possible. The generated GDS is just an approximation of the continuous structure. If you optimize for longer/make the structure more discrete, the performance should match better when you simulate.

Finally, I did check the Lumerical simulation of the device again, and though I don't get a perfect match, I do see the power switch between the arms, though rejection is not great at one of the wavelengths.

**Comment by iclibera** [comment]
Thank you for the answer! I verified with the altered code and it works well on Lumerical so far, giving the very same results as on SPINS monitor processing.

**Comment by AhmedHBayoumi** [comment]
Hello @iclibera , 

I am also trying to validate the wdm2 example using Lumerical and I am facing the same issue you faced. May you elaborate on what modifications you had to make to the code to get similar results? 

Thanks in advance.

**Comment by kaipengliuHIT** [comment]
> One possibility is that there was a GDS generation bug (now fixed) that made the GDS polygons twice as large as they were supposed to be.
> 
> Second, in the example, we aren't careful to make the optimized structure as discrete as possible. The generated GDS is just an approximation of the continuous structure. If you optimize for longer/make the structure more discrete, the performance should match better when you simulate.
> 
> Finally, I did check the Lumerical simulation of the device again, and though I don't get a perfect match, I do see the power switch between the arms, though rejection is not great at one of the wavelengths.

I am using topology optimization to make a more challenging integrated device. After reading your statement, I decided to increase the number of iterations in order to get better results in the experiment.

**Comment by kaipengliuHIT** [comment]
I spent much time to read your paper, code and the maxwellb, and have learned a lot from them. Thank you very much!!!
But the experiment is really difficult for me such as how to use the EBL ......:)

**Comment by kaipengliuHIT** [comment]
> One possibility is that there was a GDS generation bug (now fixed) that made the GDS polygons twice as large as they were supposed to be.
> 
> Second, in the example, we aren't careful to make the optimized structure as discrete as possible. The generated GDS is just an approximation of the continuous structure. If you optimize for longer/make the structure more discrete, the performance should match better when you simulate.
> 
> Finally, I did check the Lumerical simulation of the device again, and though I don't get a perfect match, I do see the power switch between the arms, though rejection is not great at one of the wavelengths.

I spent much time to read your paper, code and the maxwellb, and have learned a lot from them. Thank you very much!!!
But the experiment is really difficult for me such as how to use the EBL ......:)
