### ISSUE TITLE
Installing spins-b on mac

### ISSUE THREAD

**Issue by anthmanni** [stanfordnqp/spins-b#33]
Does Maxwell/spins work on Mac OS?

**Comment by nvsapra** [comment]
I have spins working and operational on my Mac computer.

**Comment by iclibera** [comment]
I couldn't make Maxwell work on my Mac, probably because my Mac is lacking Nvidia gpu. Maxwell eventually needs CUDA drivers installed on Mac.

Spins work well for 2D studies.

**Comment by anthmanni** [comment]
@nvsapra thank you for the response! Are you somehow able to run maxwell on your mac? I'm running into the same issue as @iclibera (thank you for your comment), where I cannot build maxwell due to lack of cuda support. Is maxwell exclusively used for 3D studies? I intend to use spins to design a 4-port beamsplitter for photonic circuits, so it could be done in 2D.
Thank you,
Anthony

**Comment by iclibera** [comment]
Hi again, sorry for interrupting this conversation.

I just wanted to note, I am also having the same problem "no module named: spins...", so I have added the following to wdm2.py just under "import numpy as np"

import sys
sys.path.append('../../../')

so then it works! You can also go ahead and type the same for the monitor processing example code. I hope this works for you as well, while I am not sure that this is a good fix.

**Comment by anthmanni** [comment]
@iclibera thank you for the suggestion! I attempted that and was given an endless loop of errors related to there being no spins module. Perhaps I entered it wrong, but given that there is no spins executable in my venv/bin, I think something is going awry with my installation.
@nvsapra might you be able to comment on the installation process using macOS Catalina, python3.8.3 or 3.7.5? I've tried sudo installs as well as virtual environments in the terminal, with the same problem appearing every time.
Thank you,
Anthony

**Comment by anthmanni** [comment]
SOLVED!
Evidently simple things are simple. All I had to do was drag the contents of the spins-b master folder into my working directory in PyCharm. I can now import all spin modules and attributes, and it runs beautifully on mac I must say. I'm using a 2015 macbook pro with only 16gb RAM, which ran the wdm2 invdes example in only 13 minutes.
Thank you for making such a clean and powerful software! Sorry for being an alarmist before attempting this simple file move.

**Comment by nvsapra** [comment]
@anthmanni Apologies for the delay in response, but glad things are working! To echo some points, @iclibera is correct, Maxwell is an iterative solver that is used for 3D simulation and relies on the requires an Nvidia GPU.

My Mac is running Python 3.7.5, but I usually run SPINS on an Ubuntu 18.04 machine using Python 3.6.9. Glad to know that higher versions work as well.
