### ISSUE TITLE
Grating coupler example: output gds file layer 100

### ISSUE THREAD

**Issue by AhmedHBayoumi** [stanfordnqp/spins-b#39]
Hello, 

I am new to inverse design and I am still getting familiar with spins. I noticed that the output gds files layer number is 100, which in the code denotes the etched silicon layer. However, I believe that it is not etched silicon, it is silicon, shouldn't it be 101 instead? 

<img width="672" alt="gds layer 100" src="https://user-images.githubusercontent.com/25781916/89334165-64a20680-d696-11ea-8d35-dc6f86b70a70.png">

Thanks.

**Comment by JesseLu** [comment]
Hi! Please let me know if this is still an issue, or if this has been resolved, thank you!

**Comment by JesseLu** [comment]
Closing for now.
