### ISSUE TITLE
wdm2 example: Is it correct to use effective index method with topology optimization?

### ISSUE THREAD

**Issue by AhmedHBayoumi** [stanfordnqp/spins-b#40]
Hi, 

I have some doubts about using the effective index method (EIM) to simulate a structure that is not slowly varying in the x-y plane. As I understand it, to use the EIM approximation the mode profile should be slowly varying in the y-direction which I believe is not the case here?

Also, I have been trying to validate the example with Lumerical 3D FDTD and 2.5D (EIM-based) FDTD and the results are totally different from spins-b's. I have used the same configurations as in the spins-b code. Any advice would be appreciated.

Thanks in advance.

Update: I should have used Lumerical 2D FDTD not 2.5D or 3D for validation. My question is, should this output be the input to the 3D optimization?

**Comment by JesseLu** [comment]
Hi! In general, you cannot automatically extract a 2D optimization/structure and expect it to work in 3D. EIM would only work well for slowly varying structures as you mention.
