### ISSUE TITLE
In the /spins/goos/schema_registry line 48, meybe the "self._stack.append(context)" should be "self._stack.append(registry)" ?

### ISSUE THREAD

**Issue by kaipengliuHIT** [stanfordnqp/spins-b#41]
In the /spins/goos/schema_registry line 48, meybe the "self._stack.append(context)" should be "self._stack.append(registry)" ?

**Comment by JesseLu** [comment]
You may indeed be correct. Would you be able to submit a pull request for this?

**Comment by JesseLu** [comment]
Closing for now.
