### ISSUE TITLE
unable to import compat

### ISSUE THREAD

**Issue by lucasnorder** [stanfordnqp/spins-b#52]
When importing the different folders to start creating my own model i get the following error message;

" Node with name {} already registered.".format(node_name))

ValueError: Node with name goos.log_print already registered.

This message already arises before defining any functions just at the start where you import the required folders and packages. Does anyone has the same issue, or know how to solve this?

**Comment by JesseLu** [comment]
Hi! Is this still an issue?

**Comment by JesseLu** [comment]
Closing for now.
