### ISSUE TITLE
How to generate gds file for final grating coupler design when using Goos grating coupler example?

### ISSUE THREAD

**Issue by msu627** [stanfordnqp/spins-b#53]
Hello, for the Goos grating coupler example, how to generate gds file for the final design?

**Comment by JesseLu** [comment]
Hi! Is this still an issue? If so, can you post how far you got? Thank you!

**Comment by jadafi** [comment]
I have actually done that by extracting the grate edges from the optimization variable. Regards

**Comment by JesseLu** [comment]
Great! Closing this.
