### ISSUE TITLE
Can't run bend90 .ipynb on Google driver

### ISSUE THREAD

**Issue by Yaqirabbit** [stanfordnqp/spins-b#56]
Hi,

I followed the recommended Spin package process to upload the folder to the Google driver.But while running the code block, there was an error with no Spin package and other errors.

![image](https://user-images.githubusercontent.com/81306139/112311082-413cd200-8ce0-11eb-87d2-137069d8fba1.png)

![image](https://user-images.githubusercontent.com/81306139/112311123-4dc12a80-8ce0-11eb-9820-73fbaff949e2.png)

I'm a beginner. Thank you for your help

**Comment by JesseLu** [comment]
Hi! Were you able to resolve this? Please let me know if you still need help and I will be happy to assist you.

**Comment by JesseLu** [comment]
Closing for now.
