### ISSUE TITLE
Convert json file to gds file

### ISSUE THREAD

**Issue by Suyichuan98** [stanfordnqp/spins-b#57]
Hello, I am going through the "bend90" example by colab-notebook. How can I get a gds file from the example by using the notebook? Currently I get the json file after running the codes. The picture is the code that I am trying to get the gds file but it shows an error "ValueError: Unknown node, got node type 'goos.function.constant' with metatype 'NodeMetaType.OPTPLAN_NODE' "
![Capture](https://user-images.githubusercontent.com/49491335/120867037-4f179a80-c54e-11eb-91f0-ff4ff6b20b91.PNG)

**Comment by JesseLu** [comment]
Hi, can you share your colab with me? It looks like you may be mixing grating and bend90 examples.

**Comment by JesseLu** [comment]
I don't see the colab. Can you share the link again?

**Comment by Suyichuan98** [comment]
Here is the link:
https://drive.google.com/file/d/1bp8FgyqD1IV3Uw-HZOoSM2m8u7-Tl6ot/view?usp=sharing

**Comment by Suyichuan98** [comment]
Here is the new link:
https://drive.google.com/file/d/1bp8FgyqD1IV3Uw-HZOoSM2m8u7-Tl6ot/view?usp=sharing

**Comment by JesseLu** [comment]
https://colab.research.google.com/drive/1bp8FgyqD1IV3Uw-HZOoSM2m8u7-Tl6ot#scrollTo=IFRivKOHUFjp

I added some cells to generate GDS. It does not seem to be straightforward to generate GDS from goos at the moment. Made other changes to the colab to remove the Google Drive dependence.
