### ISSUE TITLE
NumpyArrayType does not support complex values

### ISSUE THREAD

**Issue by kaipengliuHIT** [stanfordnqp/spins-b#58]
Hello,
 Why the NumpyArrayType does not support complex values?

**Comment by JesseLu** [comment]
I think it does, see https://github.com/stanfordnqp/spins-b/blob/9cd1510fef5abe650597fc8e66e9f6180e9a5aa4/spins/goos/optplan/schema_types.py#L49

**Comment by kaipengliuHIT** [comment]
> I think it does, see
> 
> https://github.com/stanfordnqp/spins-b/blob/9cd1510fef5abe650597fc8e66e9f6180e9a5aa4/spins/goos/optplan/schema_types.py#L49

Thank you, I will study this.

**Comment by kaipengliuHIT** [comment]
> I think it does, see
> 
> https://github.com/stanfordnqp/spins-b/blob/9cd1510fef5abe650597fc8e66e9f6180e9a5aa4/spins/goos/optplan/schema_types.py#L49

Thank you very much, I download the old code and study it and ignore the new code:)
