### ISSUE TITLE
Is BLAS necessary？

### ISSUE THREAD

**Issue by LYX-Rain** [stanfordnqp/spins-b#62]
What will happen if BLAS is not installed？
which version of BLAS (e.g. OpenBLAS, ATLAS, Intel MKL) is recommend？

**Comment by xuanlunhuang** [comment]
SLAS你是指BLAS吗？好像MKL是你装Numpy，MKL就是自带的了

**Comment by LYX-Rain** [comment]
@xuanlunhuang  Thank you
