### ISSUE TITLE
Suggestion for grating coupling - invert it

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#7]
Just a suggestion for the grating coupling problem: invert the excitation and detection (I am not an expert in this code, so I would rather wait for such example). Excite from the waveguide mode, and use overlap with Gaussian beam to find coupling efficiency. Due to the reciprocity principle the value will be the same as for direct coupling from Gaussian to waveguide mode. But benefits are following:
1) One can additionally calculate back-reflection into waveguide. It is useful when designing out-coupling gratings, where back-reflection should be minimum. This parameter can be also added as optimization objective.
2) One can put several Gaussian ports (from each side or with different sizes) and for the same simulation calculate coupling efficiencies (= overlaps) of Gaussian beams of different sizes, or of different incidence (from substrate side or from the top, or at different angles).

**Comment by VovaZen** [comment]
Would really love to have this feature:) In practice a finite back-reflection from the out-coupling grating into the waveguide will result in Fabry Perot cavity, producing oscillations in transmission spectrum...

**Comment by ludi1001** [comment]
If you really want it now, the easy thing is to add another simulation with a source injecting into the waveguide and use that for the back-reflection calculation.

**Comment by VovaZen** [comment]
Interesting idea, I will try it :) Is there a name for the source injecting into the waveguide (point dipole?), or is it just a very much confined Gaussian beam?

**Comment by VovaZen** [comment]
Just found WaveguideModeSource - will try it :)

**Comment by ludi1001** [comment]
The naive way of handling backreflection described here is now in the example.
