### ISSUE TITLE
Error when import levelset_parametrization

### ISSUE THREAD

**Issue by BravoXXX** [stanfordnqp/spins-b#77]
Hello,
  I want to add discrete optimization in wdm2.py.But when I use optplan.HermiteLevelSetParametrization,I get one import error like the following:
![image](https://user-images.githubusercontent.com/109728623/188393828-ccfd6304-f4ce-4a76-b825-0784376de950.png)
  I found that there is no levelset_parametrization.py in spins.invdes.parametrization file.Could someone add it to the repository or tell me how to add a discrete optimization in wdm2.py.?

Thank you!

**Comment by ludi1001** [comment]
Unfortunately `HermiteLevelSetParametrization` isn't in the open source version
