### ISSUE TITLE
grating couple example drops FOM after iteration 50

### ISSUE THREAD

**Issue by joamatab** [stanfordnqp/spins-b#8]
in the grating coupler optimization, why does the FOM drop around iteration 50 and does not recover after that?

![image](https://user-images.githubusercontent.com/4514346/62504091-e02f5600-b7ab-11e9-997e-3c60567e1d1b.png)

**Comment by ludi1001** [comment]
Up to iteration 50, it's running a continuous relaxation where the permittivity values are allowed to vary continuously between the device and cladding material. In addition, no fabrication constraints are enforced at this time. After iteration 50, the device is an actual discrete device with fabrication constraints enforced. See https://doi.org/10.1364/OE.26.004023 for details.

**Comment by joamatab** [comment]
Thank you Logan!
