### ISSUE TITLE
confusement in description

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#9]
in the description it says:
Requirements: Python 3.5+
and then:
Installation: $ pip install ./spins-b

Shouldn't it be pip3 instead? I know it is obvious for usual Linux users, but for noobs like me who installed Linux on virtual mashine just to run spins it took a while to realize that there are two pythons and I need to properly write it as pip3

**Comment by ludi1001** [comment]
Thanks for the feedback. The version that "pip" runs varies from system to system. Because I almost always work in a virtualenv, "pip" is always the version I want. This is a good point though, and we will also consider expanding on documentation for those unfamiliar with Python.
